services:
  - type: web
    name: smart-placement-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn placement_portal.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: placement-db
          property: connectionString
    autoDeploy: true

databases:
  - name: placement-db
    databaseName: placement_portal
    user: placement_user
